# Site settings
title: Tania's Blog
header-img: img/home-bg.png
email: tania.e.aparicio@gmail.com
copyright_name: tanelam
description: > # this means to ignore newlines until "baseurl:"
  All about learning to code.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  tanelam
learn_profile: tanelam
email_username: tania.e.aparicio@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
